SELECT ID, FISH_NAME, a.LENGTH AS LENGTH
FROM FISH_INFO a, FISH_NAME_INFO b
WHERE a.FISH_TYPE = b.FISH_TYPE and a.FISH_TYPE IN 
(
    SELECT FISH_TYPE
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    HAVING LENGTH = MAX(LENGTH)
)
ORDER BY ID