SELECT SUM(c.SCORE) AS SCORE, b.EMP_NO, b.EMP_NAME, b.POSITION, b.EMAIL
FROM HR_EMPLOYEES b
JOIN HR_GRADE c ON b.EMP_NO = c.EMP_NO
WHERE c.YEAR = '2022'
GROUP BY c.YEAR, b.EMP_NAME, b.POSITION, b.EMAIL, b.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;
